version: '3.3'

services:
  zookeeper:
    image: zookeeper
    ports:
      - "2181:2181"
  kafka:
    depends_on:
      - zookeeper
    image: confluentinc/cp-kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.1.8:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
